name: Deploy to Production

on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    environment: Production - sadforms.com
    runs-on: ubuntu-latest
    if: github.repository == 'byjackli/sadforms'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: npm ci && npm run build
      - name: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SADFORMS }}"
          channelId: live
          projectId: sadforms
