name: Deploy to Preview
"on":
  pull_request:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: Preview - sadforms.com
    if: github.repository == 'byjackli/sadforms'
    steps:
      - name: build
        uses: actions/checkout@v2
        run: npm ci && npm run build
      - name: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SADFORMS }}"
          channelId: "${{ secrets.GITHUB_RUN_ID }}"
          projectId: sadforms