name: Deploy to Preview

on:
  push:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: Preview - sadforms.com
    if: github.repository == 'byjackli/sadforms'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SADFORMS }}"
          projectId: sadforms